### ISSUE TITLE
run failed

### ISSUE THREAD

**Issue by fe3dback** [fe3dback/go-arch-lint#2]
```
go-arch-lint --project-path /home/runner/work/galaxy/galaxy
used arch file: /home/runner/work/galaxy/galaxy/.go-arch-lint.yml
        module: github.com/fe3dback/galaxy

panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 7 [running]:
sync.(*WaitGroup).Wait(0xc00001a0d0)
	/opt/hostedtoolcache/go/1.14.7/x64/src/sync/waitgroup.go:132 +0xad
github.com/fe3dback/go-arch-lint/files.(*Resolver).handleQueue.func1(0xc0003194a0, 0xc00005c060, 0xc0000a9500, 0xc00038e8a0, 0xc00038e840)
	/home/runner/go/src/github.com/fe3dback/go-arch-lint/files/resolver.go:155 +0x10d
created by github.com/fe3dback/go-arch-lint/files.(*Resolver).handleQueue
Makefile:12: recipe for target 'arch' failed
	/home/runner/go/src/github.com/fe3dback/go-arch-lint/files/resolver.go:137 +0x80
make: *** [arch] Error 2
##[error]Process completed with exit code 2.
```

**Comment by fe3dback** [comment]
Fixed in v1.1.0
