### ISSUE TITLE
Incorrect handling variadic parameters 

### ISSUE THREAD

**Issue by ilya-hontarau** [fe3dback/go-arch-lint#55]
With deepscan and variadic functions, linter exits with panic:
panic: runtime error: index out of range [1] with length 1

goroutine 340 [running]:
github.com/fe3dback/go-arch-lint/internal/services/checker/deepscan.(*Searcher).applyMethodImplementationsInPackages.func1(0x140000f7b00)
        /Users/ilyahontarau/go/src/github.com/ilya-hontarau/go-arch-lint/internal/services/checker/deepscan/searcher_find_implementations.go:137 +0x41c
github.com/fe3dback/go-arch-lint/internal/services/checker/deepscan.(*Searcher).findFunctionCalls.func1({0x10237eb78?, 0x140000f7b00})
        /Users/ilyahontarau/go/src/github.com/ilya-hontarau/go-arch-lint/internal/services/checker/deepscan/searcher_find_implementations.go:245 +0xec
go/ast.inspector.Visit(0x140006406c0, {0x10237eb78?, 0x140000f7b00?})
        /opt/homebrew/opt/go/libexec/src/go/ast/walk.go:386 +0x38
go/ast.Walk({0x102379718?, 0x140006406c0?}, {0x10237eb78, 0x140000f7b00})

**Comment by ilya-hontarau** [comment]
Added a test example in this pr https://github.com/fe3dback/go-arch-lint/pull/56
